const fs = require('fs');
const path = require('path');

module.exports = {
  onPreBuild: ({ constants, utils }) => {
    const sbUrl = process.env.SUPABASE_URL || '';
    const sbKey = process.env.SUPABASE_KEY || '';
    
    const configContent = `// Auto-generated by Netlify build plugin — DO NOT COMMIT
window.__SEASALT_SB_URL = "${sbUrl}";
window.__SEASALT_SB_KEY = "${sbKey}";
`;
    
    const publishDir = constants.PUBLISH_DIR || 'public';
    const outputPath = path.join(publishDir, '_config.js');
    
    fs.writeFileSync(outputPath, configContent, 'utf8');
    console.log(`✅ Injected Supabase config into ${outputPath}`);
  }
};
